name: Node.js CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: prebuild
        run: |
          npm ci
      - name: build
        run: |
          npm run build --if-present
      - name: quality
        run: |
          npm run lint
      - name: Deploy on GitHubPages with secret
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./dist
          token: ${{ secrets.GH_PAT }}
